name: Deploy to Amazon ECS environment based on branch

on:
  push:
    branches:
      - main
      - release
      - dev
     
env:
  ECS_TASK_DEFINITION: task-definition.json 
  CONTAINER_NAME: nginx
       
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    

    steps: 
    - name: Setting env variables for main branch
      if: ${{ github.ref == 'refs/heads/main' && always() }}
      run: |
        echo "This is running on main branch"
        AWS_REGION=ap-south-1                          # set this to your preferred AWS region, e.g. us-west-1
        ECR_REPOSITORY=leela-test-gh-actions           # set this to your Amazon ECR repository name
        ECS_SERVICE=nginx-test                         # set this to your Amazon ECS service name
        ECS_CLUSTER=leela-test-cluster                 # set this to your Amazon ECS cluster name
        environment=production                         # containerDefinitions section of your task definition    
        echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV     
        echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_ENV    
        echo "ECS_SERVICE=$ECS_SERVICE" >> $GITHUB_ENV     
        echo "ECS_CLUSTER=$ECS_CLUSTER" >> $GITHUB_ENV 
        echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV     
        echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV                                                                     
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build, tag, and push image to Amazon ECR
      run: |
        aws ecs describe-task-definition --task-definition first-run-task-definition --query taskDefinition > /home/runner/work/task-definition.json
    - name: teststes
      run: |
        ls -lrta /home/runner/work/
        cat /home/runner/work/task-definition.json
    - name: Fill in the new image ID in the Amazon ECS task definition
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: /home/runner/work/task-definition.json
        container-name: "nginx"
        image: "182093768440.dkr.ecr.ap-south-1.amazonaws.com/leela-test-gh-actions:f03e414a9aa"        
   
